server:
  port: 8081
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://172.0.0.1:3306/sell?characterEncoding=utf-8
  jpa:
    show-sql: true
logging:
  pattern:
    console:
  file:
